### ISSUE TITLE
Email Sent Twice

### ISSUE THREAD

**Issue by pauljoel** [andrewmriley/phpformmail#5]
Three days after form is completed the correct email is sent an identical message is sent again v1.06.0.

**Comment by andrewmriley** [comment]
I'm thinking its not the PHP script its self but could be either the sending or receiving mail server trying to resend for some unknown reason. The formmail script only runs for a fraction of a second when a user hits submit so it can't hang open for three days. Mail servers on the other hand do have retry periods that can last multiple days. I think this is what is happening.

I don't know what email service you use but if you search for "How to read email headers in X" and replace X with what you use like Gmail, Outlook etc you'll be able to see some information about the servers that sent it. If a mail server re-sent it you'll see similar but different headers between the two emails.

These SMTP headers are important because we'll need it to debug whats sending the duplicates. By default PHPFormMail adds in the line:

`Below is the result of your feedback form.  It was submitted by' $form['email'] . ' on ' . $mail_date`

This is important because you'll need to compare that line in the email. Is the date/time at the end of that string the same between the two different emails? If the date/time is the same you'll need to look at the email headers to see if they are different between the two emails. If they are different but the date/time in the "Below is the result" is the same than the mail server is at fault.

If the date/times don't match in the "Below is the result" lines between the two emails then it is somehow getting double submitted three days later but I don't have an idea how that would happen.

**Comment by andrewmriley** [comment]
Closing out after 14 days of inactivity.
